### ISSUE TITLE
Multiple passes that don't expire

### ISSUE THREAD

**Issue by bebogedo24** [DavidAylaian/EagleTimeCHS#22]
If a user signs up for a pass and he already has a pass, his new pass will simply be added to his passes page. On the passes page, the user can just swipe left or right to view the different passes he has, and they don't expire. TestStud account currently has two passes, one from January 21 and one from January 10.

Should students be allowed to have multiple passes? If so we must make them expire and we must add instruction telling the user to swipe left and right to view his different passes.
If not we need to make it so that the student can't sign up unless he has 0 passes with him.

**Comment by bebogedo** [comment]
Actually looks like there is a cap on how many times you can sign up at two passes. A red bar appears at the bottom when you try to sign up a third time that you can click and it will send you to the passes page.

we can modify this to stop them at one pass if we don't want them to be able to have multiple passes.

However, it looks like you can sign up for the same teacher twice.

**Comment by DavidAylaian** [comment]
We'll stop it at one pass.
